### PR TITLE
Fix Windows callback function

### LINKED ISSUE #2: opening input causes Access Violation on Windows 10
`mnOpenInput` seems to make the app crash (on Windows anyway)..

```D
import std.stdio;
import minuit;

void main(string[] args)
{
	MnInputPort[] inputDevices = mnFetchInputs();

	writeln("List of input devices:");
	foreach (MnInputPort device; inputDevices)
	{
		writeln(device.name);
	}

	MnInputHandle input = mnOpenInput(inputDevices[0]);
	mnCloseInput(input);
}
```

```
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
minuit 0.1.1: target for configuration "windows-build" is up to date.
hello_minuit ~master: building configuration "application"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running .\hello_minuit.exe 
List of input devices:
Keystation Mini 32

object.Error@(0): Access Violation
----------------
0x00402C06 in void minuit.device.winmm._mnListen(void*, uint, uint, uint, uint) at C:\Users\poeticAndroid\AppData\Local\dub\packages\minuit-0.1.1\minuit\source\minuit\device\winmm.d(239)
0x6D92DE88 in DriverCallback
0x5514CC3D
0x5514CF56
0x55142463
0x6D931968 in midiInOpen
0x0040295A in minuit.device.winmm.MnInputHandle minuit.device.winmm.mnOpenInput(minuit.device.winmm.MnInputPort) at C:\Users\poeticAndroid\AppData\Local\dub\packages\minuit-0.1.1\minuit\source\minuit\device\winmm.d(212)
0x00402314 in _Dmain at D:\code\D\hello_minuit\source\app.d(14)
0x0040CF2B in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll().__lambda1()
0x0040CEA5 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
0x0040CD40 in _d_run_main
0x0040289C in main at D:\code\D\hello_minuit\source\app.d(7)
0x00433B39 in mainCRTStartup
0x76B06359 in BaseThreadInitThunk
0x77D87A94 in RtlGetAppContainerNamedObjectPath
0x77D87A64 in RtlGetAppContainerNamedObjectPath
Program exited with code 1
```

As you can see, it can list the input devices fine and find my Keystation Mini 32, but it crashes when it tries to open it..

### PR DESCRIPTION
**Pull request by dkorpel**
The callback function is supposed to use the Windows ABI, but it previously used the D ABI which has the parameters in reverse order. It happened to work on 64-bit because dwHandle is the middle parameter and you used the `msg` parameter for the midi bytes while that is actually the message type, the midi bytes are in `dwParam1` (which took the spot of `msg` because of the wrong ABI).

I don't know exactly why it failed on 32-bit, but there was probably another register mismatch that wasn't there on 64-bit.

Closes https://github.com/Enalye/minuit/issues/2

### CODE REVIEW

**Comment by Enalye** [comment]
Wow, I don't know how you know about that but thanks you a lot !
I was getting out of ideas about how to fix that bug, your help is greatly appreciated !!

Thanks !

**Comment by dkorpel** [comment]
Funny story actually, I have been working on my own ALSA/Winmm midi input library for a while now but today I discovered this library because it was under "recently updated" on [code.dlang.org](https://code.dlang.org). I saw the issue and remembered I had the exact same problem when I wrote my Winmm callback function. 

Weird that I didn't find this library earlier, it would have saved me a lot of work :p

**Comment by Enalye** [comment]
Yeah, this library started as a simple personal library because I couldn't find any midi library available for D, much less one that handled Linux. It's far from perfect, but at least it works now, thanks to you.

Now I'm curious, you already have an alsa/winmm midi lib done ? If you already knew about this peculiar problem, yours may be more advanced than mine ?

**Comment by dkorpel** [comment]
> Now I'm curious, you already have an alsa/winmm midi lib done?

It's not done yet. I started toying with reading Midi on Windows back in January (just getting midi devices and messages printed in the terminal), then looked into Alsa for Linux in August. Since last month I am working on cleaning it up so it can be used as a library (separating concerns, making public cross-platform functions, testing etc.). The Alsa code is pretty clean now, I have a callback API but also want to provide a polling API which is WIP. Windows is still a mess.

I still plan on finishing it because it has some advantages over this library:
- it compiles with `-betterC` (consequently functions are `@nogc` and `nothrow`)
- it provides a callback API and some functions for interpreting midi events
- it gives a timestamp for midi messages

However:
- it doesn't support output (I don't have a need for that currently)
- it doesn't handle SysEx messages (though neither does this library, and I also have no need for that)
- I'm not that experienced with multi-threading so my poll queue design might be buggy / sub-optimal. Also manual memory management is risky.

I find it interesting how your ALSA code is so small btw. The ALSA documentation is extremely bare bones so I looked at some examples where they use `snd_rawmidi_poll_descriptors`, `poll` and `snd_rawmidi_poll_descriptors_revents` first but from your code it seems `snd_rawmidi_read` is all you need.

**Comment by Enalye** [comment]
Yeah, you pretty much have to do everything with only read/write functions though I don't really know what purpose those polling functions serve, maybe I missed something important ? But hey, with pretty much no documentation, we have to guess things.

I plan to handle SysEx messages and I think it might already work for Alsa but I haven't tested it yet.
I don't think I'll ever handle timestamps with this lib.
This lib is mainly for my midi viewer where I do my own timing so timestamps aren't really needed, but with multithreading so I had to deal with synchronisation issues for this.
And foremost, I try to keep the lib simple and easy to use.

So, good luck for dealing with Alsa's bullshit haha

**Pull request merged**
